name: Ping health endpoint

on:
  # Planification toutes les 10 minutes
  schedule:
    - cron: "*/10 * * * *"
  # Déclenchement manuel
  workflow_dispatch:
  # Déclenchement à chaque push sur main
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        env:
          PING_URL: ${{ secrets.PING_URL }}
        run: |
          if [ -z "$PING_URL" ]; then
            echo "Error: PING_URL not set. Add it to Settings → Secrets and variables → Actions"
            exit 1
          fi
          echo "Pinging $PING_URL ..."
          # Ping l'URL avec 3 tentatives en cas d'erreur, ignore le contenu
          curl -fsS --retry 3 -o /dev/null "$PING_URL" || { echo "Health check failed"; exit 1; }
          echo "Health check OK"
